CREATE DATABASE TEST;

/****CREATE TABLE EMP***/

CREATE TABLE EMP (
EID INT NOT NULL,
ENAME VARCHAR(30),
DEPT VARCHAR(40),
SALARY VARCHAR(30)); 

/***INSERT INTI EMP******/

INSERT INTO EMP(EID,ENAME,DEPT,SALARY)
VALUES(1,'RAM','HR',10000);
INSERT INTO EMP(EID,ENAME,DEPT,SALARY)
VALUES(2,'AMRIT','MRKT',20000);
INSERT INTO EMP(EID,ENAME,DEPT,SALARY)
VALUES(3,'RAVI','HR',30000);
INSERT INTO EMP(EID,ENAME,DEPT,SALARY)
VALUES(4,'NITIN','MRKT',40000);
INSERT INTO EMP(EID,ENAME,DEPT,SALARY)
VALUES(5,'VARUN','IT',50000);

/***SELECT ALL VALUES FROM EMP****/

SELECT * FROM EMP;

/***SELECT MAX SALARY FROM EMPLOYEE*****/

SELECT MAX(SALARY) FROM EMP;

/***SELECT EMPLOYEE NAME FROM EMP HAVING MAX SALARY***/

SELECT ENAME FROM EMP WHERE SALARY = ( SELECT MAX(SALARY) FROM EMP);

/**EXPLANATION

SELECT MAX SALARY FROM EMPLOYEE= 50000;
SALARY= 500000;
10000=50000;(FALSE)
20000=50000;(FALSE)
30000=50000;(FALSE)
40000=50000;(FALSE)
50000=50000;(TRUE)

SELECT ENMAE FROM EMP WHERE SALARY=50000;
ENMAE=VARUN;

*****/

/*** SELECT ENAME FROM FROM EMPLOYEE GETTING SECOND HIGHEST SALARY***/

SELECT ENAME FROM EMP WHERE SALARY IN (SELECT MAX(SALARY) FROM EMP WHERE SALARY <> (SELECT MAX(SALARY) FROM EMP));

/***EXPLANATION

SELECT MAX SALARY FROM EMP = 50000
WE NEED TO FIND OUT HIGHEST SALARY FROM REST ALL SARARY APART FROM 50000
 SALARY <> (SELECT MAX(SALARY) FROM EMP))= 40000
10000<>20000(TRUE)
20000<>20000(TRUE)
30000<>20000(TRUE)
40000<>20000(TRUE)
50000<>20000(FALSE
SELECT MAX(SALARY) FROM EMP WHERE SALARY TRUE VALUES= 40000
SELECT ENAME FROM EMP WHERE SALARY IN 40000
NITIN;

IN:  WHEN WE NEED TO COMPARE LEFT HAND SIDE WITH MORE THAN I VALUE
= :  WHEN WE NEED TO COMPARE LEFT HAND SIDE WITH 1 VALUE

*****/

/**** WRITE A QUERY TO DISPLAY ALL THE DEP NAMES ALONG WITH NO OF EMP WORKING IN IT  ****/

SELECT DEPT, COUNT(DEPT) FROM EMP GROUP BY DEPT;

/**** EXPLANATION

WE NEED TO DIVIDE THE DEPT AS PER NAME FOR THAT WE NEED TO USE GROUP BY

WHILE USING GROUP BY CLAUSE WE CAN SELECT SELECT SAME ATTRIBUTE WHICH ATTRIBUTE WE USED AFTER GROUP BY .
APART FROM THAT ATTRIBUTE IF WE WANT TO USE ANY OTHER ATTRIBUTE THEN WE CAN USE THOSE ATTRIBUTE WITH HELP OF AGGRIGATE FUNCTION LIKE MAX. MIN, COUNT, SUM ETC..

****/

/**  WRITE A QUERY TO DISPLAY ALL DEPT NAME WHERE NO OF EMP <2 ****/

SELECT ENAME FROM EMP WHERE DEPT IN (SELECT DEPT FROM EMP GROUP BY DEPT HAVING COUNT(DEPT) < 2);

/*** write a query to display highest salary department wise and nmae of the emp who is taking that *****/

SELECT ENAME FROM EMP WHERE SALARY IN (SELECT MAX(SALARY) FROM EMP GROUP BY DEPT);

/** select 4th highest salary ****/
SELECT EID, ENAME FROM EMP E1 WHERE 2 = (SELECT COUNT(DISTINCT SALARY) FROM EMP E2 WHERE E1.EID > E2.EID);
SELECT * FROM EMP;