CREATE DATABASE DATA;

/****CREATE TABLE EMP***/

CREATE TABLE EMPLOYEE (
EID INT NOT NULL,
ENAME VARCHAR(30),
ADDRESS VARCHAR(40)); 

/***INSERT INTI EMP******/

INSERT INTO EMPLOYEE(EID,ENAME,ADDRESS)
VALUES(1,'RAVI','CHD');
INSERT INTO EMPLOYEE(EID,ENAME,ADDRESS)
VALUES(2,'VARUN','DELHI');
INSERT INTO EMPLOYEE(EID,ENAME,ADDRESS)
VALUES(3,'NITIN','PUNE');
INSERT INTO EMPLOYEE(EID,ENAME,ADDRESS)
VALUES(4,'ROBIN','BANGALORE');
INSERT INTO EMPLOYEE(EID,ENAME,ADDRESS)
VALUES(5,'AMMY','CHD');

/****CREATE TABLE PROJECT***/

CREATE TABLE PROJECT (
EID INT NOT NULL,
PID INT NOT NULL,
PNAME VARCHAR(40),
LOCATION VARCHAR(40)); 

/***INSERT INTI PROJECT******/

INSERT INTO PROJECT(EID,PID,PNAME, LOCATION)
VALUES(1,11,'IOT','BANGALORE');
INSERT INTO PROJECT(EID,PID,PNAME, LOCATION)
VALUES(2,12,'BIGDATA','DELHI');
INSERT INTO PROJECT(EID,PID,PNAME, LOCATION)
VALUES(3,13,'RETAIL','MUMBAI');
INSERT INTO PROJECT(EID,PID,PNAME, LOCATION)
VALUES(4,14,'ANDROID','HYDERABAD');


/*** FIND DETAIL OF EMPLOYEE WHOSE ADDRESS IS DELHI OR CHD OR PUNE ****/

SELECT * FROM EMPLOYEE WHERE ADDRESS IN ('CHD', 'DELHI', 'PUNE');

/*** FIND THE DETAILS OF EMPLOYEE WHO IS WORKING AT LEAST IN ONE PROJECT**/

SELECT * FROM EMPLOYEE WHERE EXISTS (SELECT EID FROM PROJECT WHERE EMPLOYEE.EID = PROJECT.EID );

/**** NATIRAL JOIN ****/

SELECT ENAME FROM EMPLOYEE, PROJECT WHERE EMPLOYEE.EID = PROJECT.EID;

SELECT ENAME FROM EMPLOYEE NATURAL JOIN PROJECT;